DROP TABLE IF EXISTS footprints;

CREATE TABLE IF NOT EXISTS `footprints` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `group_id` VARCHAR(255) DEFAULT NULL,
  `tx_hash` VARCHAR(255) DEFAULT NULL,
  `from` VARCHAR(255) DEFAULT NULL,
  `to` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
AUTO_INCREMENT=1;

